name = "Tilde"
uuid = "73a6ac3c-4b34-4cca-a813-308f7589d80d"
authors = ["Chad Scherrer <chad.scherrer@gmail.com> and contributors"]
version = "0.1.2"

[deps]
Accessors = "7d9f7c33-5ae7-4f3b-8dc6-eff91059b697"
ArrayInterface = "4fba245c-0d91-5ea0-9b3e-6abc04ee57a9"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
DensityInterface = "b429d917-457f-4dbc-8f4c-0cc954292b1d"
DiffResults = "163ba53b-c6d8-5494-b064-1a9d43ac40c5"
IfElse = "615f187c-cbe4-4ef1-ba3b-2fcf58d6d173"
JuliaVariables = "b14d175d-62b4-44ba-8fb7-3064adc8c3ec"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MLStyle = "d8e11817-5142-5d16-987a-aa16d5891078"
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
MappedArrays = "dbb5928d-eab1-5f90-85c2-b9b0edb7c900"
MeasureBase = "fa1605e6-acd5-459c-a1e6-7e635759db14"
MeasureTheory = "eadaa1a4-d27c-401d-8699-e962e1bbc33b"
NamedTupleTools = "d9ec5142-1e00-5aa0-9d6a-321866360f50"
NestedTuples = "a734d2a7-8d68-409b-9419-626914d4061d"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
RuntimeGeneratedFunctions = "7e49a35a-f44a-4d26-94aa-eba1b4ca6b47"
SampleChains = "754583d1-7fc4-4dab-93b5-5eaca5c9622e"
Serialization = "9e88b42a-f829-5b0c-bbe9-9e923198166b"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
Static = "aedffcd0-7271-4cad-89d0-dc628f76c6d3"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
StatsFuns = "4c63d2b9-4356-54db-8cca-17b64c39e42c"
TransformVariables = "84d833dd-6860-57f9-a1a7-6da5db126cff"
Tricks = "410a4b4d-49e4-4fbc-ab6d-cb71b17b3775"
TupleVectors = "615932cf-77b6-4358-adcd-5b7eba981d7e"

[compat]
Accessors = "0.1"
ArrayInterface = "4, 5, 6"
DataStructures = "0.18"
DensityInterface = "0.4"
DiffResults = "1"
IfElse = "0.1"
JuliaVariables = "0.2"
MLStyle = "0.3,0.4"
MacroTools = "0.5"
MappedArrays = "0.3, 0.4"
MeasureBase = "0.9"
MeasureTheory = "0.16"
NamedTupleTools = "0.12, 0.13, 0.14"
NestedTuples = "0.3"
RecipesBase = "1"
Reexport = "1"
Requires = "1"
RuntimeGeneratedFunctions = "0.5"
SampleChains = "0.5"
SpecialFunctions = "1, 2"
Static = "0.5, 0.6"
StatsBase = "0.33"
StatsFuns = "0.9, 1"
TransformVariables = "0.5, 0.6"
Tricks = "0.1"
TupleVectors = "0.1"
julia = "1.5"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
JET = "c3a54625-cd67-489e-a8e7-0a5a0ff4e31b"
Literate = "98b081ad-f1c9-55d3-8b20-4c87d4299306"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SampleChainsDynamicHMC = "6d9fd711-e8b2-4778-9c70-c1dfb499d4c4"
StableRNGs = "860ef19b-820b-49d6-a774-d7a799459cd3"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "Documenter", "Literate", "Plots", "Random", "SampleChainsDynamicHMC", "StableRNGs", "Test", "JET"]
